"""Kitchen planning package."""

from auto_design.planner.feasibility import (
    MIN_I_RUN_MM,
    MIN_PREP_COUNTER_MM,
    MIN_TOPOLOGY_LEG_MM,
    MIN_WALKWAY_CLEARANCE_MM,
    STANDARD_BASE_DEPTH_MM,
    AvailableWallRun,
    FeasibilityResult,
    RequiredFootprintItem,
    TopologyFit,
    allowed_wall_runs,
    analyze_feasibility,
    analyze_topology_fits,
    required_appliance_footprint_mm,
    required_footprint_items,
)
from auto_design.planner.grammar import (
    FAMILY_LABELS,
    GRAMMAR_VARIANTS,
    WALLS_PER_FAMILY,
    GrammarStep,
    KitchenTopologyTemplate,
    RunSegmentTemplate,
    generate_topology_templates,
)
from auto_design.planner.placement import (
    MAX_CONTINUITY_GAP_MM,
    BaseCoverage,
    PlacedItem,
    PlacementPlan,
    PlacementRun,
    generate_placement_plan,
)
from auto_design.planner.zones import (
    ZONE_ORDER,
    ItemZoneAssignment,
    MacroZonePlan,
    ZoneAssignment,
    plan_zones_for_template,
)

__all__ = [
    "MIN_I_RUN_MM",
    "MIN_PREP_COUNTER_MM",
    "MIN_TOPOLOGY_LEG_MM",
    "MIN_WALKWAY_CLEARANCE_MM",
    "STANDARD_BASE_DEPTH_MM",
    "AvailableWallRun",
    "FeasibilityResult",
    "RequiredFootprintItem",
    "TopologyFit",
    "FAMILY_LABELS",
    "GRAMMAR_VARIANTS",
    "GrammarStep",
    "KitchenTopologyTemplate",
    "ItemZoneAssignment",
    "MacroZonePlan",
    "MAX_CONTINUITY_GAP_MM",
    "BaseCoverage",
    "PlacedItem",
    "PlacementPlan",
    "PlacementRun",
    "allowed_wall_runs",
    "analyze_feasibility",
    "analyze_topology_fits",
    "generate_topology_templates",
    "generate_placement_plan",
    "plan_zones_for_template",
    "required_appliance_footprint_mm",
    "required_footprint_items",
    "RunSegmentTemplate",
    "WALLS_PER_FAMILY",
    "ZONE_ORDER",
    "ZoneAssignment",
]
